name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Install dependencies
      run: |
        composer install --no-dev --optimize-autoloader
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_oracle_a_diep }}
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@168.138.213.251 << 'EOF'
          cd /home/ubuntu/lavarel
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          sudo systemctl restart apache2 
        EOF
